#quickbite github ci
name: Deploy to EC2
on:
  push:
    branches:
      - develop  
jobs:
  deploy:
    runs-on: ubuntu-latest
    env:
      EC2_USER: ubuntu
      EC2_HOST: 18.142.51.145 

    steps:
      - name: Checkout source code
        uses: actions/checkout@v4

      - name: Setup SSH key
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.EC2_SSH_PUBLIC_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan -H $EC2_HOST >> ~/.ssh/known_hosts

      - name: Deploy via SSH
        run: |
          ssh -i ~/.ssh/id_rsa $EC2_USER@$EC2_HOST << 'EOF'
            set -e
            cd /home/ubuntu/data/quickbite-project/
            ls -al
            git pull origin main
            cd /home/ubuntu/data/quickbite-project/logic
            ls -al
            chmod +x *
            pm2 start "./mvnw spring-boot:run" --name logic
            cd /home/ubuntu/data/quickbite-project/gateway
            ls -al
            chmod +x *
            pm2 start "./mvnw spring-boot:run" --name gateway
            cd /home/ubuntu/data/quickbite-project/frontend
            ls -al
            chmod +x *
            #pwd
            #whoami
            npm install
            pm2 start "npm run dev -- --host" --name frontend
            pm2 list
            #pm2 restart all || npm run start
          EOF
